branches:
  only:
  - devops
# ensure that docker is available on the travis machine
services:
  - docker

addons:
  ssh_known_hosts: ec2-54-87-37-72.compute-1.amazonaws.com

before_install:
  - openssl aes-256-cbc -K $encrypted_0af220062a29_key -iv $encrypted_0af220062a29_iv -in arno.pem.enc -out /tmp/arno.pem -d
  - chmod 400 /tmp/arno.pem

script:
  - docker-compose up -d bdd
  - docker-compose build back front
  - docker-compose up -d
  - docker-compose ps
  - sleep 5
  - curl -X GET -I http://localhost:3000/health
  - sh scripts/create_roles.sh
  - sh scripts/create_dummy_user.sh

deploy:
  provider: script
  skip-cleanup: true
  script: ssh -i "/tmp/arno.pem" ubuntu@ec2-54-87-37-72.compute-1.amazonaws.com sh ~/Time_Manager/scripts/deploy.sh


notifications:
  webhooks: https://outlook.office.com/webhook/33e7d83a-5fa1-4393-8876-71ba84c1c630@901cb4ca-b862-4029-9306-e5cd0f6d9f86/TravisCI/ca95adeb5df44b0593ad99b698ae057f/6d65da65-2cda-4dbd-bff5-fbaea78c2ff8
