branches:
  only:
  - devops
# ensure that docker is available on the travis machine
services:
  - docker

script:
  - docker-compose build back front bdd
  - docker-compose up -d
  - curl -X GET -I http://localhost:3000/health
  - sh create_roles.sh
  - sh create_dummy_user.sh