branches:
  only:
  - devops
# ensure that docker is available on the travis machine
services:
  - docker

script:
  - docker-compose build back front bdd
  - docker-compose up -d
  - docker-compose ps
  - sleep 5
  - curl -X GET -I http://localhost:3000/health
  - sh create_roles.sh
  - sh create_dummy_user.sh

notifications:
  webhooks: https://outlook.office.com/webhook/33e7d83a-5fa1-4393-8876-71ba84c1c630@901cb4ca-b862-4029-9306-e5cd0f6d9f86/TravisCI/ca95adeb5df44b0593ad99b698ae057f/6d65da65-2cda-4dbd-bff5-fbaea78c2ff8
